# Generated by Django 6.0.5 on 2026-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XSSEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.BigIntegerField()),
                ("label", models.CharField(max_length=16)),
                ("probability", models.FloatField()),
                ("features", models.JSONField()),
                ("latency_ms", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "XSS Event",
                "ordering": ["-created_at"],
            },
        ),
    ]
